name: null
favicon: null
layout_spectrum: 0.06388
typography_spectrum: 0.66046
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#fefefe'
    - '#494949'
    - '#b7b7b7'
    - '#969696'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
