name: Jagwar Live
favicon: null
layout_spectrum: 0
typography_spectrum: 0.51581
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-65581513-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#fefefe'
    - '#494949'
    - '#b7b7b7'
    - '#969696'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.125
  rhythmicContrast: 0
purpose: []
